// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  invitations: {
    count: createApiLeaf<"query", typeof import("../functions/invitations").count>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").count>("invitations:count"), { type: "query" }),
    create: createApiLeaf<"mutation", typeof import("../functions/invitations").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").create>("invitations:create"), { type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/invitations").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").list>("invitations:list"), { type: "query" }),
    revoke: createApiLeaf<"mutation", typeof import("../functions/invitations").revoke>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").revoke>("invitations:revoke"), { type: "mutation" }),
  },
  session: {
    me: createApiLeaf<"query", typeof import("../functions/session").me>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/session").me>("session:me"), { type: "query" }),
    signIn: createApiLeaf<"mutation", typeof import("../functions/session").signIn>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").signIn>("session:signIn"), { type: "mutation" }),
    signOut: createApiLeaf<"mutation", typeof import("../functions/session").signOut>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").signOut>("session:signOut"), { type: "mutation" }),
  },
  signup: {
    signUpWithInvitation: createApiLeaf<"mutation", typeof import("../functions/signup").signUpWithInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/signup").signUpWithInvitation>("signup:signUpWithInvitation"), { type: "mutation" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
