// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  invitations: {
    count: createApiLeaf<"query", typeof import("../functions/invitations").count>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").count>("invitations:count"), { auth: "required", type: "query" }),
    create: createApiLeaf<"mutation", typeof import("../functions/invitations").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").create>("invitations:create"), { auth: "required", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/invitations").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").list>("invitations:list"), { auth: "required", type: "query" }),
    revoke: createApiLeaf<"mutation", typeof import("../functions/invitations").revoke>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").revoke>("invitations:revoke"), { auth: "required", type: "mutation" }),
  },
  signup: {
    signUpWithInvitation: createApiLeaf<"mutation", typeof import("../functions/signup").signUpWithInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/signup").signUpWithInvitation>("signup:signUpWithInvitation"), { type: "mutation" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
