// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  invitations: {
    count: createApiLeaf<"query", typeof import("../functions/invitations").count>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").count>("invitations:count"), { type: "query" }),
    create: createApiLeaf<"mutation", typeof import("../functions/invitations").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").create>("invitations:create"), { type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/invitations").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/invitations").list>("invitations:list"), { type: "query" }),
    revoke: createApiLeaf<"mutation", typeof import("../functions/invitations").revoke>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/invitations").revoke>("invitations:revoke"), { type: "mutation" }),
  },
  session: {
    countByUser: createApiLeaf<"query", typeof import("../functions/session").countByUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/session").countByUser>("session:countByUser"), { type: "query" }),
    heartbeat: createApiLeaf<"mutation", typeof import("../functions/session").heartbeat>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").heartbeat>("session:heartbeat"), { type: "mutation" }),
    listByUser: createApiLeaf<"query", typeof import("../functions/session").listByUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/session").listByUser>("session:listByUser"), { type: "query" }),
    me: createApiLeaf<"query", typeof import("../functions/session").me>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/session").me>("session:me"), { type: "query" }),
    revoke: createApiLeaf<"mutation", typeof import("../functions/session").revoke>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").revoke>("session:revoke"), { type: "mutation" }),
    revokeAllForUser: createApiLeaf<"mutation", typeof import("../functions/session").revokeAllForUser>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").revokeAllForUser>("session:revokeAllForUser"), { type: "mutation" }),
    signIn: createApiLeaf<"mutation", typeof import("../functions/session").signIn>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").signIn>("session:signIn"), { type: "mutation" }),
    signOut: createApiLeaf<"mutation", typeof import("../functions/session").signOut>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/session").signOut>("session:signOut"), { type: "mutation" }),
  },
  settings: {
    getRegistrationSettings: createApiLeaf<"query", typeof import("../functions/settings").getRegistrationSettings>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/settings").getRegistrationSettings>("settings:getRegistrationSettings"), { type: "query" }),
    setRequireInvitationCode: createApiLeaf<"mutation", typeof import("../functions/settings").setRequireInvitationCode>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/settings").setRequireInvitationCode>("settings:setRequireInvitationCode"), { type: "mutation" }),
  },
  signup: {
    signUpWithInvitation: createApiLeaf<"mutation", typeof import("../functions/signup").signUpWithInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/signup").signUpWithInvitation>("signup:signUpWithInvitation"), { type: "mutation" }),
  },
  users: {
    count: createApiLeaf<"query", typeof import("../functions/users").count>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/users").count>("users:count"), { type: "query" }),
    get: createApiLeaf<"query", typeof import("../functions/users").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/users").get>("users:get"), { type: "query" }),
    list: createApiLeaf<"query", typeof import("../functions/users").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/users").list>("users:list"), { type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
